apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicio-token-sorteo
spec:
  replicas: 1  # La réplica inicial mínima
  selector:
    matchLabels:
      app: servicio-token-sorteo
  template:
    metadata:
      labels:
        app: servicio-token-sorteo
    spec:
      containers:
        - name: servicio-token-sorteo
          image: lauml/dssd-java-api-ecocycle:1.0.0
          ports:
            - containerPort: 8081
          env:
            - name: DB_SORTEO_URL
              valueFrom:
                secretKeyRef:
                  name: api-sorteo-secrets
                  key: DB_API_URL
            - name: DB_SORTEO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-sorteo-secrets
                  key: DB_SORTEO_USERNAME
            - name: DB_API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-sorteo-secrets
                  key: DB_SORTEO_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
