apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicio-token-sorteo
spec:
  replicas: 1  # La réplica inicial mínima
  selector:
    matchLabels:
      role: servicio-token-sorteo
  template:
    metadata:
      labels:
        role: servicio-token-sorteo
    spec:
      containers:
        - name: servicio-token-sorteo
          image: lauml/dssd-api-sorteo-kubernetes:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-sorteo-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-sorteo-secrets
                  key: DB_PASSWORD
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: api-sorteo-secrets
                  key: DB_URL
          resources:
            requests:
              cpu: "64m"  # Reduces la solicitud de CPU
              memory: "256Mi"
            limits:
              cpu: "128m"  # Limita el consumo de CPU
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 120  # Espera 4 minutos antes del primer chequeo
            periodSeconds: 15  # Intervalo de 15 segundos entre los chequeos
            failureThreshold: 15  # 10 fallos consecutivos antes de reiniciar
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 120  # Espera 4 minutos antes del primer chequeo
            periodSeconds: 15  # Intervalo de 15 segundos entre los chequeos
            failureThreshold: 15  # 15 fallos consecutivos antes de marcar como no listo

---

apiVersion: v1
kind: Service
metadata:
  name: servicio-token-sorteo
spec:
    selector:
        role: servicio-token-sorteo
    ports:
      - port: 8080
        targetPort: 8080
    type: LoadBalancer
