apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicio-token-sorteo
spec:
  replicas: 3  # La réplica inicial mínima
  selector:
    matchLabels:
      app: servicio-token-sorteo
  template:
    metadata:
      labels:
        app: servicio-token-sorteo
    spec:
      containers:
        - name: servicio-token-sorteo
          image: lauml/dssd-api-sorteo-kubernetes:latest
          ports:
            - containerPort: 8081
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-sorteo-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-sorteo-secrets
                  key: DB_PASSWORD
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: api-sorteo-secrets
                  key: DB_URL
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: servicio-token-sorteo
spec:
    selector:
        app: servicio-token-sorteo
    ports:
      - port: 8080
        targetPort: 8081
    type: LoadBalancer
