apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: java-sorteo-db
spec:
  serviceName: "java-sorteo-db"
  replicas: 1  # Mínimo de réplicas
  selector:
    matchLabels:
      app: java-sorteo-db
  template:
    metadata:
      labels:
        app: java-sorteo-db
    spec:
      containers:
        - name: java-sorteo-db
          image: postgres:16.1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: api-sorteo-secrets
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-sorteo-secrets
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: api-sorteo-secrets
                  key: DB_NAME
          volumeMounts:
            - name: java-sorteo-db-pvc
              mountPath: /var/lib/postgresql/data
              subPath: sorteo-db
      volumes:
        - name: java-sorteo-db-pvc
          persistentVolumeClaim:
            claimName: java-sorteo-db-pvc

          
---
apiVersion: v1
kind: Service
metadata:
  name: java-sorteo-db
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: java-sorteo-db
