apiVersion: batch/v1
kind: CronJob
metadata:
  name: realizar-sorteo
spec:
  schedule: "35 19 28 * *" # Día correspondiente a la generación del sorteo
  jobTemplate:
    spec:
      activeDeadlineSeconds: 210
      template:
        spec:
          containers:
            - name: realizar-sorteo-job
              image: lauml/dssd-api-sorteo-kubernetes:latest
              env:
                - name: TASK
                  value: "realizarSorteo" # Configura la tarea
          restartPolicy: OnFailure
