apiVersion: batch/v1
kind: CronJob
metadata:
  name: realizar-sorteo
spec:
  schedule: "4 16 13 * *" # Día correspondiente a la generación del sorteo
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sorteo-job
              image: tu-imagen-java:latest
              env:
                - name: TASK
                  value: "realizarSorteo" # Configura la tarea
          restartPolicy: OnFailure
